apiVersion: v1
kind: Service
metadata:
  name: {{ include "bb-noti.fullname" . }}-follower
  namespace: {{ .Release.Namespace }}
  labels: {{ include "bb-noti.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
  selector:
    {{- include "bb-noti.selectorLabels" . | nindent 4 }}
    node-role: follower
